### ISSUE TITLE
PvP時の無敵効果音について

### ISSUE THREAD

**Issue by uTen2c** [gutitubo/SiegeBattle#1]
1.9から無敵時間にエンティティを殴ると「entity.player.attack.nodamage」の音がなるようになったんですけど、連打してると少しその音が気になるので、消してみたらどうでしょうか？
消すにはパケットを破棄する必要があるので、かんたんに扱えるように簡単なパケットリスナーを作ってみたので良かったら使ってみてください。

https://github.com/uTen2c/SimplePacketListener

あと、これをここに書こうか意見フォームに書こうか迷ったんですけど、どっちに書いたほうがいいですか？

**Comment by gutitubo** [comment]
ありがとうございます

ここに書いてくれるとエンジニアっぽくていい感じなのでここに書いてくれると嬉しいです

**Comment by uTen2c** [comment]
了解です！

コード系の提案とかはこっちで書かせてもらいます。
